
<h1>NOCtools - Cisco Discovery Protocol Utilities</h1>

<br />

{OSS_Message}

<div class="row">

    <div class="span3">
        <h3>CDP Neighbours</h3>

        <p>
            Enter an IP address / hostname below
            to discover its CDP neighbors via
            SNMP.
        </p>
        <form action="{genUrl controller="cdp" action="neighbours"}" method="post">
            <input type="text" class="span3" name="cdp_root"
                value="{if isset( $cdp_root )}{$cdp_root}{elseif isset( $options.cdp.default_root )}{$options.cdp.default_root}{/if}"
                placeholder="IP / Hostname..."
            />
            <input type="submit" class="btn" />
        </form>
    </div>

    <div class="span3">
        <h3>CDP L2 Topology</h3>

        <p>
            This utility will create an L2 topology graph from a root
            node traversing each neighbour recursivily.
        </p>
        <p>
            <a class="btn" href="{genUrl controller="cdp" action="l2-topology"}">L2 Topology &raquo;</a>
        </p>
    </div>

    <div class="span3">
    </div>

    <div class="span3">
    </div>

</div>

