
<h1>NOCtools - Cisco Discovery Protocol Utilities</h1>

<br />

{OSS_Message}

<div class="row">

    <div class="span3">
        <h3>CDP Neighbours</h3>

        <p>
            Enter an IP address / hostname below
            to discover its CDP neighbors via
            SNMP.
        </p>
        <form action="{genUrl controller="cdp" action="neighbours"}" method="post">
            {if isset( $_devices ) and count( $_devices )}
                <select name="cdp_root" data-placeholder="Choose a device..." class="chzn-select span3">
                {foreach $_devices as $d}
                    <option value="{$d}" {if ( isset( $cdp_root ) and $cdp_root eq $d ) or ( !isset( $cdp_root ) and isset( $options.cdp.default_root ) and $options.cdp.default_root eq $d )}selected="selected"{/if}>{$d}</option>
                {/foreach}
                </select>
            {else}
                <input type="text" class="span3" name="cdp_root"
                    value="{if isset( $cdp_root )}{$cdp_root}{elseif isset( $options.cdp.default_root )}{$options.cdp.default_root}{/if}"
                    placeholder="IP / Hostname..."
                />
            {/if}
            <br /><br />
            <input type="submit" class="btn" />
        </form>
    </div>

    <div class="span3">
        <h3>CDP L2 Topology</h3>

        <p>
            This utility will create an L2 topology graph from a root
            node traversing each neighbour recursivily.
        </p>
        <p>
            <a class="btn" href="{genUrl controller="cdp" action="l2-topology"}">L2 Topology &raquo;</a>
        </p>
    </div>

    <div class="span3">
    </div>

    <div class="span3">
    </div>


</div>

