{include file="header.phtml"}

<div class="container">

<h1>NOCtools - Cisco Discovery Protocol Utilities - {$type|upper} Topology &amp; Port Roles</h1>

<br />

{OSS_Message}

<div class="row">

    <div class="span12">
        <p>
            This utility will graph your RSTP L2 topology based on CDP neighbours for a given VLAN.
        </p>
        <p>
            Start by entering the <em>root node</em> where CDP discovery will start, edit the
            CDP hosts you want to ignore (will not appear on graph at all) and select the RSTP VLAN / MST instance
            you are interested in to generate the graph.
        </p>
    </div>
</div>

<div class="row">

    <div class="span12 well">
        <form action="{genUrl controller="cdp" action="stp-topology" type=$type}" method="post">

        <div class="span3">
                <label>Root Node IP / Hostname:</label>
                {if isset( $_devices ) and count( $_devices )}
                    <select name="cdp_root" data-placeholder="Choose a device..." class="chzn-select span3" id="cdp_root">
                    <option></option>
                    {foreach $_devices as $d}
                        <option value="{$d}" {if ( isset( $cdp_root ) and $cdp_root eq $d ) or ( !isset( $cdp_root ) and isset( $options.cdp.default_root ) and $options.cdp.default_root eq $d )}selected="selected"{/if}>{$d}</option>
                    {/foreach}
                    </select>
                {else}
                    <input type="text" class="span3" name="cdp_root"
                        value="{if isset( $cdp_root )}{$cdp_root}{elseif isset( $options.cdp.default_root )}{$options.cdp.default_root}{/if}"
                        placeholder="IP / Hostname..."
                    />
                {/if}
                <br /><br />
                <input type="submit" name="submit" value="Download DOT File" class="btn" />
                <input type="submit" name="submit" value="Generate &raquo;" class="btn btn-success" />
        </div>

        <div class="span5">
                <label>List of CDP neighbour names to ignore - one per line:</label>
                <textarea class="span5" name="ignoreList" rows="4">{$ignoreList}</textarea>
        </div>

        <div class="span3">
            <label>{if $type eq 'mst'}MST Instance{else}RSTP VLAN{/if}:</label>

            <select name="instance" id="instance" data-placeholder="Choose a {if $type eq 'mst'}MST Instance{else}VLAN{/if}..." class="chzn-select span3">
                <option></option>
                {if isset( $instances ) and is_array( $instances )}
                    {foreach $instances as $iid => $iname}
                        <option value="{$iid}" {if isset( $instance ) and $iid eq $instance}selected="selected"{/if}>{$iid} - {$iname}</option>
                    {/foreach}
                {/if}
            </select>
            <br /><br />
            <label for="excludeNonParticipants" class="checkbox">
                <input type="checkbox" name="excludeNonParticipants" id="excludeNonParticipants" value="1" {if isset( $excludeNonParticipants ) and $excludeNonParticipants}checked="checked"{/if} />
                Exclude non-participating nodes
            </label>
            <label for="showPortRoles" class="checkbox">
                <input type="checkbox" name="showPortRoles" id="showPortRoles" value="1" {if isset( $showPortRoles ) and $showPortRoles}checked="checked"{/if} />
                Show {if $type eq 'mst'}MST{else}RSTP{/if} Port Roles
            </label><br />

        </div>

        </form>
    </div>
</div>

{if isset( $file )}

    {if isset( $showPortRoles ) and $showPortRoles}
        <div class="row">
            <div class="span3">&nbsp;</div>
            <div class="span6">
                <strong>Port Roles:</strong>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="label" style="background-color: #6495ED;">ROOT</span>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="label" style="background-color: #00ff00;">DESIGNATED</span>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="label" style="background-color: red;">ALTERNATE</span>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="label" style="background-color: orange;">BACKUP</span>
            </div>
        </div>
    {/if}

    <ul class="thumbnails">
        <li class="span12">
            <a href="{genUrl controller="cdp" action="img-stp-topology" file=$file}" target="_blank">
                <img src="{genUrl controller="cdp" action="img-stp-topology" file=$file}" />
            </a>
        </li>
    </ul>

{/if}


</div>

<script>

$().ready( function(){

    $( "#cdp_root" ).on( 'change', function( event ) {
        $( "#instance" ).attr( 'disabled', 'disabled' );

        $( "#instance" ).html( '<option>Loading...</option>' ).val( "" );
        $( "#instance" ).trigger( "liszt:updated" );

        {if $type eq 'mst'}
            $.getJSON( "{genUrl controller='stp' action='ajax-get-mst-instances-for-host'}/host/"
        {else}
            $.getJSON( "{genUrl controller='vlan' action='ajax-get-for-host'}/host/"
        {/if}
                + encodeURIComponent( $( "#cdp_root" ).val() ), function( j ){
    
            var options = "<option></option>\n";

            $.each( j, function(key, val) {
                options += "<option value=\"" + key + "\">" + key + " - " + val + "</option>\n";
            });

            $( "#instance" ).html( options );
            $( "#instance" ).trigger( "liszt:updated" );
        });

        $( "#instance" ).removeAttr( 'disabled' );
    });
});

</script>


{include file="footer.phtml"}
