
<div class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            <p class="navbar-text">
                NOCtools V{$smarty.const.APPLICATION_VERSION}.
                
                &copy; Copyright 2012 {if $smarty.now|date_format:"%Y" neq '2012'} - {$smarty.now|date_format:"%Y"}{/if}
                <a href="http://www.opensolutions.ie/">Open Source Solutions Limited</a>.
                These Programs are provided AS IS, without warranty.
                Licensed under the <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html">GNU GPL v3</a>.
                <a href="https://github.com/opensolutions/NOCtools">Fork me on GitHub</a>.
            </p>
            </ul>
        </div>
    </div>
</div>

</body>

</html>
