<!DOCTYPE html>
<html>

<head>
    <title>phpNOCtools by Open Solutions</title>

    <meta charset="utf-8">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta http-equiv="content-language" content="en" />

    <meta name="author" content="www.opensolutions.ie" />
    <meta name="owner" content="www.opensolutions.ie" />

    {include file='header-css.phtml'}
    {include file='header-js.phtml'}

</head>

<body style="margin-top: 20px; background-color: white;">

{include file='menu.phtml'}

