
<div class="navbar  navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{genUrl}">NOCtools</a>

            <ul class="nav">
                <li {if $controller eq 'index'}class="active"{/if}>
                    <a href="{genUrl}">Home</a>
                </li>
                <li {if $controller eq 'cdp'}class="active"{/if}>
                    <a href="{genUrl controller="cdp"}">CDP</a>
                </li>
                <li {if $controller eq 'stp'}class="active"{/if}>
                    <a href="{genUrl controller="stp"}">STP</a>
                </li>
                <li {if $controller eq 'vlan'}class="active"{/if}>
                    <a href="{genUrl controller="vlan"}">VLAN</a>
                </li>
            </ul>
        </div>
    </div>
</div>

