
<div class="navbar  navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{genUrl}">NOCtools</a>

            <ul class="nav">
                <li {if $controller eq 'index'}class="active"{/if}>
                    <a href="{genUrl}">Home</a>
                </li>
                {if !isset( $options.controller.asterisk.enabled ) or $options.controller.asterisk.enabled}
                    <li {if $controller eq 'asterisk'}class="active"{/if}>
                        <a href="{genUrl controller="asterisk"}">Asterisk</a>
                    </li>
                {/if}
                {if !isset( $options.controller.bgp.enabled ) or $options.controller.bgp.enabled}
                    <li {if $controller eq 'bgp'}class="active"{/if}>
                        <a href="{genUrl controller="bgp"}">BGP</a>
                    </li>
                {/if}
                {if !isset( $options.controller.cdp.enabled ) or $options.controller.cdp.enabled}
                    <li {if $controller eq 'cdp'}class="active"{/if}>
                        <a href="{genUrl controller="cdp"}">CDP</a>
                    </li>
                {/if}
                {if !isset( $options.controller.stp.enabled ) or $options.controller.stp.enabled}
                    <li {if $controller eq 'stp'}class="active"{/if}>
                        <a href="{genUrl controller="stp"}">STP</a>
                    </li>
                {/if}
                {if !isset( $options.controller.vlan.enabled ) or $options.controller.vlan.enabled}
                    <li {if $controller eq 'vlan'}class="active"{/if}>
                        <a href="{genUrl controller="vlan"}">VLAN</a>
                    </li>
                {/if}
            </ul>
        </div>
    </div>
</div>

