{include file="header.phtml"}

<div class="container">

<h1>NOCtools - VLAN Utilities - Availability / Comparison</h1>

<br />

{OSS_Message}

<div class="row">

    <div class="span12">
        <p>
            This tool will allow you to see what VLANs are available on a switch
            and perform a side by side comparison with other switch(es).<br />
            Additionally name mismatches will be highlighted when / if they occur.
        </p>
    </div>
</div>

<div class="row">

    <div class="span12 well">
        <form action="{genUrl controller="vlan" action="compare"}" method="post">

        <div class="span3">
                <label>Source Node IP / Hostname:</label>
                {if isset( $_devices ) and count( $_devices )}
                    <select name="source" data-placeholder="Choose a device..." class="chzn-select span3">
                    {foreach $_devices as $d}
                        <option value="{$d}" {if ( isset( $source ) and $source eq $d ) or ( !isset( $source ) and isset( $options.cdp.default_root ) and $options.cdp.default_root eq $d )}selected="selected"{/if}>{$d}</option>{$d}</option>
                    {/foreach}
                    </select>
                {else}
                    <input type="text" class="span3" name="source"
                        value="{if isset( $source )}{$source}{elseif isset( $options.cdp.default_root )}{$options.cdp.default_root}{/if}"
                        placeholder="IP / Hostname..."
                    />
                {/if}
                <br /><br />
                <input type="submit" value="Submit &raquo;" class="btn" />
        </div>

        <div class="span6">
                <label>List of optional device(s) to compare with:</label>
                    <select data-placeholder="Choose optional device(s)..." class="chzn-select span3" multiple="multiple" name="odevices[]">
                    {foreach $_devices as $d}
                        <option value="{$d}"
                                {if isset( $odevices ) and is_array( $odevices ) and in_array( $d, $odevices )}selected="selected"{/if}
                            >{$d}</option>
                    {/foreach}
                </select>
        </div>

        </form>
    </div>
</div>

{if isset( $allVlans )}

{if count( $devices_vlans ) gt 1}
    <h4>
        Comparison of
        {foreach $devices_vlans as $device => $vlans}
            {$device}{if not $vlans@last}, {/if}
        {/foreach}
        (in order):
    </h4>
{/if}

<table class="table">
<thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        {if count( $devices_vlans ) gt 1}
            {foreach $devices_vlans as $device => $vlans}
                <th>{substr( $device, 0, strpos( $device, '.' ) )}</th>
            {/foreach}
        {else}
            <th>{$source}</th>
        {/if}
    </tr>
</thead>
<tbody>
{foreach $allVlans as $vid => $vname}
    <tr>
        <td>{$vid}</td>
        <td>{$vname}</td>
        {foreach $devices_vlans as $device => $vlans}
            <td>
                {if isset( $vlans.$vid )}
                    {if isset( $nameMismatch.$device.$vid ) and $nameMismatch.$device.$vid}
                        <span class="label label-warning"><i class="icon-warning-sign icon-white"></i>&nbsp;{$vlans.$vid}</span>
                    {else}
                        <span class="badge badge-success"><i class="icon-ok icon-white"></i></span>
                    {/if}
                {else}
                    <span class="badge badge-important"><i class="icon-remove icon-white"></i></span>
                {/if}
            </td>
        {/foreach}
    </tr>
{/foreach}
</tbody>
</table>


<br /><br /><br />


{/if} {* if isset( $allVlans ) *}

</div>

{include file="footer.phtml"}
