
<h1>NOCtools - VLAN Utilities</h1>

<br />

{OSS_Message}

<div class="row">

    <div class="span3">
        <h3>Availability / Comparison</h3>

        <p>
            This tool will allow you to see what VLANs are available on a switch
            and perform a side by side comparison with other switch(es).
        </p>
        <p>
            <a class="btn" href="{genUrl controller="vlan" action="compare"}">VLAN Comparison &raquo;</a>
        </p>
    </div>

    <div class="span3">
    </div>

    <div class="span3">
    </div>

    <div class="span3">
    </div>


</div>

