
<h1>NOCtools - BGP Utilities</h1>

<br />

<div class="row">

    <div class="span3">
        <h3>BGP Summary Table</h3>

        <p>
            This tool will perform the equivalent of a <code>show bgp summary</code>
            on a Cisco router.
        </p>
        <p>
            {if isset( $_devices ) and count( $_devices )}
            <form action="{genUrl controller="bgp" action="summary"}" method="post">
                <select name="bgpDevice" data-placeholder="Choose a device..." class="chzn-select span3">
                    <option></option>
                    {foreach $_devices as $d}
                        <option value="{$d}" {if isset( $bgpDevice ) and $bgpDevice eq $d}selected="selected"{/if}>{$d}</option>
                    {/foreach}
                </select>
                <br /><br />
                <input type="submit" value="Submit &raquo;" class="btn" />
                </form>
            {else}
                <span class="label label-important">ERROR</span> No devices defined in:<br /><br />
                <code>application/configs/devices.ini</code>
            {/if}
        </p>
    </div>

    <div class="span3">
    </div>

    <div class="span3">
    </div>

    <div class="span3">
    </div>


</div>

{OSS_Message}

