{include file="header.phtml"}

<div class="container">

<div class="hero-unit">
    <h1>NOCtools</h1>

    <p>
        Welcome to NOCtools. A mixed bag collection of tools and utilities for NOC engineers.
    </p>
    <p>
        Developed by <a href="http://www.opensolutions.ie/">Open Solutions</a>, Dublin, Ireland - <em>Internet infrasructure specialists</em>.
    </p>
</div>


<div class="row-fluid">

    <div class="span4">
        <h3>Welcome to NOCtools</h3>

        <p>
            <strong>NOCtools</strong> is a mixed bag of tools and utilities that are useful for NOC engineers.
            This project originally started out as a way to highlight and utilise our
            <a href="https://github.com/opensolutions/OSS_SNMP">OSS_SNMP</a> library (<em>a PHP SNMP library
            for people who hate SNMP</em>).
        </p>
        <p>
            It since grew into a way to graphically present information on network topology that is normally
            difficult and cumbersome to do by logging into individual devices. Such information includes a
            discovered L2 topology by CDP, using this to present rapid-PVST port roles and so forth.

        </p>
    </div>

    <div class="span4">
        <h3>Behind the Tools</h3>

        <p>
            <strong>NOCtools</strong> is written in <a href="http://www.php.net">PHP</a> using the
            <a href="http://framework.zend.com/">Zend Framework</a> (V1.x) as the application controller
            and using <a href="http://www.smarty.net/">Smarty</a> as the templating engine.
            There is no real reliance on external libraries besides
            both of these and <a href="https://github.com/opensolutions/OSS_SNMP">OSS_SNMP</a> (which requires
            some of the new features of PHP 5.4). The frontend is thanks to
            <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>.
        </p>
        <p>
            <strong>NOCtools</strong> is open source software which is hosted on
            <a href="https://github.com/opensolutions/NOCtools">GitHub</a>. You can fork us, follow us,
            raise tickets and - hopefully - raise some pull requests with new tools and features!
        </p>
    </div>


    <div class="span4">
        <h3>License and Redistribution</h3>
        <p>
            <strong>NOCtools</strong> is free software: you can redistribute it and/or modify
            it under the terms of the GNU
            <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html">General Public License</a>
            as published by the Free Software Foundation, either version 3 of the License, or
            (at your option) any later version.
        </p>
        <p>
            <strong>NOCtools</strong> is distributed in the hope that it will be useful,
            but WITHOUT ANY WARRANTY; without even the implied warranty of
            MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.  See the
            GNU General Public License for more details.
        </p>
    </div>

</div>


</div>

{include file="footer.phtml"}
